version: "3.9"

services:
  web:
    build: .
    command: daphne config.asgi:application --bind 0.0.0.0 --port 8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - ./:/cmp_api_python/
      - static_volume:/cmp_api_python/static
      - media_volume:/cmp_api_python/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql:rw

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./data/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - static_volume:/cmp_api_python/static
      - media_volume:/cmp_api_python/media

volumes:
  db_data:
  backup_db_data:
  static_volume:
  media_volume:
