version: "3.9"

services:
  web:
    container_name: django_api
    build: .
    command: daphne config.asgi:application --bind 0.0.0.0 --port 8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - ./:/cmp_api_python/
      - static_volume:/cmp_api_python/static
      - media_volume:/cmp_api_python/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: django_db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql:rw

  nginx:
    container_name: django_nginx
    image: nginx:1.21.6-alpine
    ports:
      - 80:80
    volumes:
      - ./data/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - static_volume:/cmp_api_python/static
      - media_volume:/cmp_api_python/media

  redis:
    container_name: django_redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery_worker:
    container_name: django_celery_worker
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/cmp_api_python/
    depends_on:
      - redis
    env_file:
      - ./.env

  celery_beat:
    container_name: django_celery_beat
    build: .
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/cmp_api_python/
    depends_on:
      - redis
    env_file:
      - ./.env

volumes:
  db_data:
  backup_db_data:
  static_volume:
    external: true
  media_volume:
    external: true
